Feature/organizations map
noesya/osuny-hugo-theme-aaa pull request #100
Opened 2023-03-09 14:30 UTC by Olivia206

2023-03-10 11:31 UTC, alexisben requested changes

2023-03-10 11:31 UTC, alexisben commented on assets/js/main.js
> +import './theme/blocks/partners';
L'import du script ne doit pas se faire dans ce fichier

2023-03-10 11:31 UTC, alexisben commented on layouts/partials/blocks/templates/partners.html
>  {{ $latitude := "latitude" }}
Pourquoi mettre des chaînes de caractères par défaut ?

2023-03-10 15:45 UTC, Olivia206 commented on assets/js/main.js
> +import './theme/blocks/partners';
c'est corrigé !

2023-03-13 08:42 UTC, arnaudlevy reviewed
enlever le console.log

2023-03-13 08:49 UTC, merged