Style/footer social [DRAFT]
noesya/osuny-hugo-theme-aaa pull request #149
Opened 2023-09-20 12:50 UTC by Olivia206

TODO : ajout des bonnes icons

2023-09-20 14:56 UTC, arnaudlevy approved these changes
J'approuve mais en vrai j'en sais rien ;)

2023-09-22 07:45 UTC, alexisben requested changes

2023-09-22 07:45 UTC, alexisben commented on layouts/partials/footer/social.html
> +{{ else if $menu }}
En fait il faut conserver les deux listes !

2023-09-22 08:08 UTC, Olivia206 commented on layouts/partials/footer/social.html
> +{{ else if $menu }}
c'est corrigé !

2023-09-22 08:10 UTC, merged