Moteur de recherche avec Pagefind
noesya/osuny-hugo-theme-aaa pull request #151
Opened 2023-09-21 10:18 UTC by arnaudlevy

Fix #150

2023-09-29 13:13 UTC, alexisben requested changes

2023-09-29 13:13 UTC, alexisben commented on assets/sass/_theme/design-system/search.sass
> +            top: calc(#{half($spacing4)} + (#{$spacing1} / 2))
```suggestion
            top: calc(#{half($spacing4)} + #{half($spacing1)})
```

2023-09-29 13:13 UTC, alexisben commented on bin/osuny.js
> +console.log("");
Ugly

2023-09-29 13:13 UTC, alexisben commented on assets/sass/_theme/design-system/search.sass
> +            padding-right: half($spacing1) !important
Pas fan du !important, possible d'affiner le sélecteur pour éviter ça ?

2023-09-29 13:13 UTC, alexisben commented on config.yaml
> +  search:
Il faut merge les params de "search", il y a 2 fois la clé au même niveau

2023-09-29 13:42 UTC, Olivia206 commented on assets/sass/_theme/design-system/search.sass
> +            padding-right: half($spacing1) !important
C'est style inline de Pagefind 
<img width="848" alt="Capture d’écran 2023-09-29 à 15 41 22" src="https://github.com/noesya/osuny-hugo-theme-aaa/assets/91660674/dcb220d8-6635-4257-9873-57fb9a81c681">

(Mais je vais voir pour les autres !important)

2023-10-02 15:00 UTC, alexisben requested changes

2023-10-02 15:00 UTC, alexisben commented on yarn.lock
> +<<<<<<< HEAD
```suggestion
```

2023-10-02 15:00 UTC, alexisben commented on yarn.lock
> +>>>>>>> main
```suggestion
```

2023-10-03 08:37 UTC, merged