Front/fixes
noesya/osuny-hugo-theme-aaa pull request #165
Opened 2023-10-06 08:22 UTC by Olivia206

2023-10-11 07:01 UTC, arnaudlevy commented
@Olivia206 il te manque des choses ?

2023-10-11 10:10 UTC, Olivia206 commented
Quand tu auras le temps, je veux bien une relecture @alexisben, s'il te plaît !

2023-10-11 16:09 UTC, alexisben commented
Attention ça casse sur certains breakpoints : 

![image](https://github.com/noesya/osuny-hugo-theme-aaa/assets/4630530/f95b46a0-95ac-4401-aff6-e89ce3956f07)

2023-10-11 16:09 UTC, alexisben requested changes
Bien tester block persons car ça casse sur certains affichages et on perd le double colonnage (voir screenshot)

2023-10-11 16:10 UTC, alexisben commented
![image](https://github.com/noesya/osuny-hugo-theme-aaa/assets/4630530/94172a87-f85d-4e7f-9bc0-c11697400275)

2023-10-16 13:04 UTC, alexisben commented
Grosse erreur d'affichage en pleine largeur : 

![image](https://github.com/noesya/osuny-hugo-theme-aaa/assets/4630530/2a8aac3b-cb40-4d56-b352-237682d567a1)

2023-10-16 13:11 UTC, alexisben requested changes
Problème dans le contexte block person pleine largeur sans texte long

2023-11-11 22:30 UTC, alexisben commented
Toujours pas bon

<img width="1109" alt="image" src="https://github.com/noesya/osuny-hugo-theme-aaa/assets/4630530/f92a54d0-fb0a-4023-a75e-14a968233e22">

2023-11-20 15:44 UTC, closed without merging

2023-11-20 15:47 UTC, arnaudlevy commented
On abandonne ?