Features/player video
noesya/osuny-hugo-theme-aaa pull request #167
Opened 2023-10-10 15:34 UTC by Olivia206

2023-10-10 19:10 UTC, arnaudlevy commented
@Olivia206 je prépare ça ici https://github.com/noesya/osuny/pull/1321
```
contents:
  - kind: block
    template: video
    title: >-
      Youtube
    position: 1
    data:
      url: >-
        https://www.youtube.com/watch?v=BqLgZOmqBDA

      video_title: >-
        

      video_iframe: >-
        <iframe class="youtube" loading="lazy" src="https://www.youtube.com/embed/BqLgZOmqBDA" title=""></iframe>
      video: 
        platform: "youtube"
        identifier: "BqLgZOmqBDA"
        poster: >-
          https://img.youtube.com/vi/BqLgZOmqBDA/hqdefault.jpg
        embed: >-
          https://www.youtube.com/embed/BqLgZOmqBDA
        iframe: >-
          <iframe class="youtube" loading="lazy" src="https://www.youtube.com/embed/BqLgZOmqBDA" title=""></iframe>
      transcription: >-
        



  - kind: block
    template: video
    title: >-
      Vimeo
    position: 2
    data:
      url: >-
        https://vimeo.com/715280780

      video_title: >-
        

      video_iframe: >-
        <iframe class="vimeo" loading="lazy" src="https://player.vimeo.com/video/715280780" title=""></iframe>
      video: 
        platform: "vimeo"
        identifier: "715280780"
        poster: >-
          https://vumbnail.com/715280780.jpg
        embed: >-
          https://player.vimeo.com/video/715280780
        iframe: >-
          <iframe class="vimeo" loading="lazy" src="https://player.vimeo.com/video/715280780" title=""></iframe>
      transcription: >-
        



  - kind: block
    template: video
    title: >-
      Dailymotion
    position: 3
    data:
      url: >-
        https://www.dailymotion.com/video/x8lyp39

      video_title: >-
        

      video_iframe: >-
        <iframe class="dailymotion" loading="lazy" src="https://www.dailymotion.com/embed/video/x8lyp39" title=""></iframe>
      video: 
        platform: "dailymotion"
        identifier: "x8lyp39"
        poster: >-
          https://www.dailymotion.com/thumbnail/video/x8lyp39
        embed: >-
          https://www.dailymotion.com/embed/video/x8lyp39
        iframe: >-
          <iframe class="dailymotion" loading="lazy" src="https://www.dailymotion.com/embed/video/x8lyp39" title=""></iframe>
      transcription: >-
        



  - kind: block
    template: video
    title: >-
      Peertube
    position: 4
    data:
      url: >-
        https://peertube.fr/w/orrn5AqC1ueLWEgaq6bECc

      video_title: >-
        

      video_iframe: >-
        <iframe class="peertube" loading="lazy" src="https://peertube.fr/videos/embed/orrn5AqC1ueLWEgaq6bECc" title=""></iframe>
      video: 
        platform: "peertube"
        identifier: "orrn5AqC1ueLWEgaq6bECc"
        poster: >-
          
        embed: >-
          https://peertube.fr/videos/embed/orrn5AqC1ueLWEgaq6bECc
        iframe: >-
          <iframe class="peertube" loading="lazy" src="https://peertube.fr/videos/embed/orrn5AqC1ueLWEgaq6bECc" title=""></iframe>
      transcription: >-
```

2023-10-11 16:33 UTC, alexisben requested changes

2023-10-11 16:33 UTC, alexisben commented on layouts/partials/blocks/templates/video.html
> +            "position" .block.position
Attention ! tu es dans un {{ with .block.data }} du coup impossible d'accéder à  {{ .block }}  !! Pourquoi avoir enlever la variable ?

2023-10-11 16:33 UTC, alexisben commented on layouts/partials/blocks/templates/video/dailymotion.html
> +{{ $title := .title }}
Ce template est plus ou moins répété 4x pourquoi ? et pourquoi peertube n'a pas de cover ?

2023-10-11 16:33 UTC, alexisben commented on assets/js/theme/blocks/videos.js
> +        }
```suggestion
        if (!this.player) {
            return; 
        }
        this.playBtn = this.player.querySelector('button');
```

2023-10-11 16:55 UTC, Olivia206 commented on assets/js/theme/blocks/videos.js
> +        }
Merci !

2023-10-11 16:58 UTC, Olivia206 commented on layouts/partials/blocks/templates/video.html
> +            "position" .block.position
@arnaudlevy

2023-10-11 16:59 UTC, Olivia206 commented on layouts/partials/blocks/templates/video/dailymotion.html
> +{{ $title := .title }}
Impossible d'accéder aux posters de Peertube, ou alors on n'a pas trouvé :/
Et pour la première question, @arnaudlevy

2023-10-11 17:02 UTC, Olivia206 commented on layouts/partials/blocks/templates/video.html
> +            {{ end }}
Merci !

2023-10-12 05:14 UTC, arnaudlevy commented on layouts/partials/blocks/templates/video.html
> +            "position" .block.position
Erreur de ma part !
Je la remets.

2023-10-12 05:15 UTC, arnaudlevy commented on layouts/partials/blocks/templates/video/dailymotion.html
> +{{ $title := .title }}
Parce que plus ou moins !
Peertube ne semble pas fournir de cover.

2023-10-12 05:55 UTC, arnaudlevy commented on layouts/partials/blocks/templates/video/dailymotion.html
> +{{ $title := .title }}
J'ai pré calculé le title et corrigé des petits trucs

2023-10-16 08:58 UTC, merged