add link to agenda in event blocks
noesya/osuny-hugo-theme-aaa pull request #253
Opened 2024-01-08 11:13 UTC by Olivia206

- [ ] Ajout du lien vers l'agenda (ou la catégorie)
- [ ] Reprise du nom d'une variable pour les posts

2024-01-08 14:02 UTC, alexisben requested changes

2024-01-08 14:02 UTC, alexisben commented on layouts/partials/blocks/templates/agenda.html
> +    {{- $term = site.GetPage (printf "/posts_categories%s" .category) -}}
Oups

2024-01-08 14:02 UTC, alexisben commented on layouts/partials/blocks/templates/posts.html
> +          {{ $posts_page_link := false }}
Renommer la variable

2024-01-08 16:48 UTC, Olivia206 commented
Il manque la catégorie dans les datas du bloc event : 

<img width="459" alt="Capture d’écran 2024-01-08 à 17 46 39" src="https://github.com/noesya/ffpapf/assets/91660674/b5fd9a2b-dafe-4a03-885a-46ad6c8396b1">

Pour que ce soit comme le bloc post : 

<img width="338" alt="Capture d’écran 2024-01-08 à 17 47 31" src="https://github.com/noesya/ffpapf/assets/91660674/d989ca7b-9bd1-46a6-b811-b70cec00b0c3">

2024-01-15 16:44 UTC, alexisben commented
@arnaudlevy t'as vu ça ?

2024-01-15 17:55 UTC, arnaudlevy commented
Non, c'est pour moi. ?

2024-01-16 07:39 UTC, arnaudlevy approved these changes
J'ai juste relu, il y a une attribution en 2 passes que je ne comprends pas, mais je n'ai pas vu de pb.

2024-01-16 07:39 UTC, arnaudlevy commented on layouts/partials/blocks/templates/agenda.html
> +        {{ $events_link := false }}
Pourquoi ne pas établir directement la valeur ?

2024-01-16 07:40 UTC, arnaudlevy commented
Ah je viens de comprendre, j'ai un truc à faire dans le static. Je m'en occupe !

2024-01-16 14:00 UTC, arnaudlevy commented
@alexisben j'ai fait ma partie, ça part en prod

2024-01-16 18:12 UTC, alexisben commented on layouts/partials/blocks/templates/agenda.html
> +        {{ $events_link := false }}
tu as raison ce n'est pas utile et il manque la gestion du lien de la catégorie sélectionnée du coup

2024-01-16 21:14 UTC, alexisben commented
Il faudra revenir sur un point à ton retour @Olivia206, il y a un beau bug qui bloque la compilation depuis un mois. Tu l'as corrigé dans cette PR, c'est super, mais il n'y a eu aucun échange sur le caractère d'urgence de ce bug et la nécessité de vite passer cette PR !

<img width="906" alt="image" src="https://github.com/noesya/osuny-hugo-theme-aaa/assets/4630530/2e25cd45-073e-411b-ad37-f7461c89a3f5">

<img width="721" alt="image" src="https://github.com/noesya/osuny-hugo-theme-aaa/assets/4630530/4a0f8f2d-00fd-45d2-8df3-79402ebc6f71">

2024-01-16 21:18 UTC, merged